/** File generated by config-loader type generator - DO NOT MODIFY */

export interface auth {
    issuer: string;
    access_token_exp: string;
    refresh_token_exp: string;
    private_key_path: string;
    public_key_path: string;
}