/** File generated by config-loader type generator - DO NOT MODIFY */

export interface cdn {
    upload_folder: string;
    avatars_folder: string;
    chat_images_folder: string;
    temp_folder: string;
}