/** File generated by config-loader type generator - DO NOT MODIFY */

export interface notifications {
    android: {
        channels: {
            parties: string;
            friends: string;
            chat: string;
        };
    };
}