/** File generated by config-loader type generator - DO NOT MODIFY */

import {
    api
} from "./interfaces/api";
import {
    auth
} from "./interfaces/auth";
import {
    cdn
} from "./interfaces/cdn";
import {
    notifications
} from "./interfaces/notifications";

export interface IConfigData {
    api: api;
    auth: auth;
    cdn: cdn;
    notifications: notifications;
};